### ISSUE TITLE
Address Verify("abce") returns no error?

### ISSUE THREAD

**Issue by GeniusWiki** [AfterShip/email-verifier#10]
For invalid syntax email address, the Verify() func returns err is nil.   For example

```
emailverifier.NewVerifier()
ret, verifyErr := verifier.Verify("abce")
// verifyErr is nil 
```

In code,  I think at least here will return a error, rather than nil?

```
	if !syntax.Valid {
		return &ret, nil
	}

```

**Comment by lryong** [comment]
I think it is more appropriate to return directly here, because the email address is checked and the result is **syntax invalid**, and no error occurred in the checking process. 

A better way to handle this would be to check if the syntax is valid after a email verification ?

**Comment by GeniusWiki** [comment]
That is OK if it returns nil, but in README, it doesn't mention that. It is easy to misunderstand if err==nil, it is a valid email. 

I have already changed my check as this.   

```
ret, verifyErr := verifier.Verify(email)
if verifyErr != nil || !ret.Syntax.Valid {
// invalid
}
```

**Comment by lryong** [comment]
Yes, the README is still not clear enough. 

Thanks for the suggestion, I will improve the examples for checking email addresses in the next update

**Comment by lryong** [comment]
Hi @GeniusWiki  We have update the examples. https://github.com/AfterShip/email-verifier/pull/11

**Comment by lryong** [comment]
close the ticket
