### ISSUE TITLE
Fix: Default FromEmail/HelloName values causing incorrect "deliverable" results

### ISSUE THREAD

**Issue by emilianocalzada** [AfterShip/email-verifier#133]
Hey! 👋

The current default values for "FromEmail" and "HelloName" are causing incorrect "deliverable" results during SMTP checks. Would be great to update these defaults in the package.

It currently gives the following error (with some providers):
```bash
550 5.7.27 Sender address rejected: Domain example.org does not accept mail (nullMX) error
``` 

Quick fix:
Update the default from email and hello name.
```go
verifier := emailverifier.NewVerifier().
    FromEmail("email@gmail.com").
    HelloName("gmail.com")
```

To the maintainers of this repo, i recommend updating the default values for this fields 👍 

This is the fix to this related issue: https://github.com/AfterShip/email-verifier/issues/72

Thanks, hope it helps

**Comment by NexaVerse-AI** [comment]
Change them and use your domain
