### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by dl95** [AfterShip/email-verifier#18]
I am unable to run this code . can you please let us know the process. how to run this code. its showing error 
**main.go:6:2: found packages emailverifier (address.go) and main (main.go) in /Users/user/workplace/email-verifier**

![Screenshot 2021-05-12 at 1 08 13 AM](https://user-images.githubusercontent.com/26005136/117874438-98155f80-b2be-11eb-9714-ec31d919b620.png)

**Comment by lryong** [comment]
@dl95  We don't provide the `main.go` file, it looks like you put the *main()* entry under this lib.

You can write a separate `demo.go` and load **email-verifer** and you should be fine.

Refer to the following code (`demo.go`) in [README](https://github.com/AfterShip/email-verifier/blob/main/README.md):

```go
package main

import (
	"fmt"
	
	emailverifier "github.com/AfterShip/email-verifier"
)

var (
	verifier = emailverifier.NewVerifier()
)


func main() {
	email := "example@exampledomain.org"

	ret, err := verifier.Verify(email)
	if err != nil {
		fmt.Println("verify email address failed, error is: ", err)
		return
	}
	if !ret.Syntax.Valid {
		fmt.Println("email address syntax is invalid")
		return
	}

	fmt.Println("email validation result", ret)
}

```

**Comment by dl95** [comment]
I did this. when i run the code the its showing error.
**main.go:6:2: found packages emailverifier (address.go) and main (main.go) in /Users/user/workplace/email-verifier**

**Comment by lryong** [comment]
I make a demo by importing `email-verifier` and everything seems fine. 
The following are my steps:

1. Creating a demo directory: `mkdir /tmp/email-verifier`
2. make `main.go` file as mention above
3. use *go modules* to init dependency requirements: `go mod init email-verifier`
4. download dependency: `go mod init`
5. run my demo: `go run main.go`

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/11936678/117963961-9cd82300-b353-11eb-81ae-689386bf33bc.png">

@dl95  I'm not quite sure what step you're having trouble with, do you want to rebuild and try again?

**Comment by dl95** [comment]
Thank You so much now it's running
