### ISSUE TITLE
Gravatar is always valid.

### ISSUE THREAD

**Issue by maranqz** [AfterShip/email-verifier#19]
Even if the gravatar image does not exist the verifier return true and a link.

The URL should have `d` parameter to get 404 code from gravatar.
For example, `https://www.gravatar.com/avatar/00000000000000000000000000000001?d=404`
instead of `https://www.gravatar.com/avatar/00000000000000000000000000000001`

**Comment by lryong** [comment]
Yes, I was able to reproduce the problem you mentioned in my local tests.

This is a great issue!  Would you like to create a PR?

**Comment by maranqz** [comment]
No, I won't.

**Comment by lryong** [comment]
OK

**Comment by lryong** [comment]
@maranqz  

The use of the `d` parameter in your example is wrong, it means the default image.
Reference: https://en.gravatar.com/site/implement/images/

**Comment by maranqz** [comment]
https://en.gravatar.com/site/implement/images/#:~:text=combining%20parameters
