### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tomaswarynyca** [AfterShip/email-verifier#23]
Is the project ready to release a new version with the improvements?

**Comment by lryong** [comment]
Yes, we plan to release a new version today

**Comment by lryong** [comment]
@tomaswarynyca  new version [v1.1.0](https://github.com/AfterShip/email-verifier/releases/tag/v1.1.0) has been released

**Comment by tomaswarynyca** [comment]
Great! @lryong 
I was looking at the changes, why is the api a BREAKING CHANGE?
The api is just an example for people who want it as a microservice.
The rest of the changes are great and more optimized!!

**Comment by lryong** [comment]
Yes, there was a problem with the description of the release, this version is more about doing some optimization work. 
The description has been updated over. 
Thank you for your approval of the project!

**Comment by tomaswarynyca** [comment]
Great project! @lryong 
Now we need to fix the changelog #25

**Comment by lryong** [comment]
@tomaswarynyca  OK, https://github.com/AfterShip/email-verifier/pull/25 has been merged.

**Comment by tomaswarynyca** [comment]
Great @lryong! Thanks for the corrections and the project!
