### ISSUE TITLE
README seems outdated re: source of disposable emails

### ISSUE THREAD

**Issue by daisy1754** [AfterShip/email-verifier#34]
README says disposable emails are from https://github.com/disposable/disposable but by looking at update.sh it seems it's coming from https://github.com/ivolo/disposable-email-domains

Can you confirm README is outdated? Also I'm curious about reasoning behind switch :)

**Comment by lryong** [comment]
Yes,  README documentation is incorrectly referencing the source of disposable emails. The disposable dataset is now updated from [ivolo/disposable-email-domains](https://github.com/ivolo/disposable-email-domains)

Maybe we posted the wrong reference link when we wrote README which referred to multiple other data sources.

 [update.sh](https://github.com/AfterShip/email-verifier/blob/main/cmd/build_metadata/update.sh) refers to [freemail](https://github.com/willwhite/freemail/blob/master/update).
