### ISSUE TITLE
proxy server

### ISSUE THREAD

**Issue by augustin-rialan** [AfterShip/email-verifier#40]
Great work!
Is there a way to use the smtp go client through a SOCKS proxy?
Thank you

**Comment by lryong** [comment]
@augustin-rialan Currently not supported, but it will be an awesome feature, Would you be willing to make a PR?

**Comment by lryong** [comment]
@augustin-rialan 
Yes, email-verifier now support verifier email address through a proxy: https://github.com/AfterShip/email-verifier/pull/48
