### ISSUE TITLE
 Having issue with verifying emails of custom domain

### ISSUE THREAD

**Issue by eeeeeeeeeee555** [AfterShip/email-verifier#43]
> tuyensinh@ued.udn.vn
> ajdsghfdjhgr4@ued.udn.vn

I tried to test 2 email address with your library but it is giving same answer although the second one isn't existed. Can you tell me what wrong I did ?

This is result I got:
`smtp validation result:  &{true false true false false}`

**Comment by lryong** [comment]
@eeeeeeeeeee555 I tested the two email addresses you provided above，the results of the validation are as follows：

```json
{
    "email": "tuyensinh@ued.udn.vn",
    "disposable": false,
    "reachable": "unknown",
    "role_account": false,
    "free": false,
    "syntax": {
        "username": "tuyensinh",
        "domain": "ued.udn.vn",
        "valid": true
    },
    "has_mx_records": true,
    "smtp": {
        "host_exists": true,
        "full_inbox": false,
        "catch_all": true,
        "deliverable": false,
        "disabled": false
    },
    "gravatar": null,
    "suggestion": ""
}
{
    "email": "ajdsghfdjhgr4@ued.udn.vn",
    "disposable": false,
    "reachable": "unknown",
    "role_account": false,
    "free": false,
    "syntax": {
        "username": "ajdsghfdjhgr4",
        "domain": "ued.udn.vn",
        "valid": true
    },
    "has_mx_records": true,
    "smtp": {
        "host_exists": true,
        "full_inbox": false,
        "catch_all": true,
        "deliverable": false,
        "disabled": false
    },
    "gravatar": null,
    "suggestion": ""
}
```

The reachability of both email addresses is **unknown**, because there is no way to determine whether the specific email recipient（via **smtp.deliverabl**e field） can receive the email.

**Comment by eeeeeeeeeee555** [comment]
hi,
I tried some verifier services and they can detect if the email address is valid or not
For example:
https://hunter.io/verify/tuyensinh@ued.udn.vn
https://hunter.io/verify/ajdsghfdjhgr4@ued.udn.vn

How they can detect it ?

**Comment by eeeeeeeeeee555** [comment]
i think some email providers blocked ip from using smtp. So, that is reason I only can verify Gmail address, not hotmail and others

**Comment by lryong** [comment]
@eeeeeeeeeee555  Yes, many SMTP ports being blocked by the ISP，you can find technical support and ask them how to implement email verification.（I think they has their unblocked SMTP ports）
