### ISSUE TITLE
Failed when check STMP use SOCKS5 proxy

### ISSUE THREAD

**Issue by sangtm-04** [AfterShip/email-verifier#51]
Hi there,
I tried to use the new feature "Support Use the specified SOCKS5 proxy host to perform email verification" of @lryong 
When I check smtp, the response is:
"check smtp failed: EOF : EOF"
I debugged, the code throw exception in function NewClient() (located in file stmp.go), in line 64 when call text.ReadResponse(220)
Please help me for that.

**Comment by nandhamurali** [comment]
@lryong Would you be able to try SOCK5 proxy with username:password? I also facing the same error, not able to resolve. smtp.newClient() gives error when using proxy?

**Comment by nandhamurali** [comment]
@sangtm-04 Were you able to fix the issue? I am also having the same issue?

**Comment by sangtm-04** [comment]
> @sangtm-04 Were you able to fix the issue? I am also having the same issue?

Sorry man, I could not fix the issue. So I decided to use Reacher instead
(https://github.com/reacherhq/backend)

**Comment by lryong** [comment]
@nandhamurali It should be possible, I've been busy lately and need to find time to look at this issue. Valid PR's are welcome!

**Comment by nandhamurali** [comment]
@lryong I am not familiar with network programming, that's where I am stuck and not able to proceed further. If you could help me, I appreciate it.

**Comment by nandhamurali** [comment]
> > @sangtm-04 Were you able to fix the issue? I am also having the same issue?
> 
> Sorry man, I could not fix the issue. So I decided to use Reacher instead (https://github.com/reacherhq/backend)

Thanks for your reply.

**Comment by devlamine** [comment]
I have the same problem, why in the doc it is indicated "with EnableSMTPCheck() to enable such capability if port 25 is usable, or use a socks proxy to connect over SMTP" we can understand with this sentence that the arrival of socks proxy solve the problem of SMTP with port 25 while the problem persists

**Comment by michele31337** [comment]
This is a very old bug, years go by and Google doesn't solve it, the problem is in net/smtp related to textproto, I was only able to reproduce this error using socks5. this bug is not related to email-verifier, I'm rewriting net/smtp using bufio instead of textproto

**Comment by emilianocalzada** [comment]
@michele31337 any updates?

im facing this issue now :(

**Comment by nandhamurali** [comment]
Issue is because the PORT 25 is not opened, you need to have a proxy with PORT 25 opened.
