### ISSUE TITLE
Wrong Results On Verification Of Outlook Emails

### ISSUE THREAD

**Issue by Blacklion14** [AfterShip/email-verifier#55]
On verifying emails of outlook domain from verifier, it gives reachable: no for emails which actually exists and are currently in use.

These are the results on verification of a valid email address :

{
email: "ratnesh.xdeliver@outlook.com",
reachable: "no",
syntax: {
username: "ratnesh.xdeliver",
domain: "outlook.com",
valid: true,
},
smtp: {
host_exists: true,
full_inbox: false,
catch_all: false,
deliverable: false,
disabled: false,
},
gravatar: null,
suggestion: "",
disposable: false,
role_account: false,
free: true,
has_mx_records: true,
}

Please review and provide solution or reasons @lryong .
Thank You!!

**Comment by lryong** [comment]
@Blacklion14 

We send an RCPT request to the target mailbox through an smtp client and only mark the reachable field as true if there is a correct response (`smtp.deliverable==true`) from the other side.

The outlook mailbox should have restrictions on external RCPT, so this is probably a false alarm. We haven't had time to do research on outlook mailbox check reachability, so we welcome the community to share the existing solutions.

**Comment by kish123-lav** [comment]
have u checked like A record , DNS validation , and the reputation of the domain we use these matters right if this is done i think we could this issues might be
