### ISSUE TITLE
Failed when check STMP use SOCKS5 proxy

### ISSUE THREAD

**Issue by devlamine** [AfterShip/email-verifier#64]
I have the same problem, why in the doc it is indicated "**with EnableSMTPCheck() to enable such capability if port 25 is usable, or use a socks proxy to connect over SMTP**" we can understand with this sentence that the arrival of socks proxy solve the problem of SMTP with port 25 while the problem persists

_Originally posted by @devlamine in https://github.com/AfterShip/email-verifier/issues/51#issuecomment-1214186744_

**Comment by lryong** [comment]
Hi, @devlamine  The latest code has fixed this issue, try to see if it has solved your problem
