### ISSUE TITLE
data file load issue if compile and runtime are in different computer

### ISSUE THREAD

**Issue by GeniusWiki** [AfterShip/email-verifier#7]
In your documentation, there is no mention that this library has a dependency on the data folder.  Until I want to compile my code on the CI server and deploy it to the production server. I found this library loading data file base on runtime.Caller(). However, runtime.Caller returns the compiled GOPATH instead of the real "runtime" path. This makes this cross-machine deployment impossible. https://stackoverflow.com/questions/51368837/golang-runtime-package-sets-filepaths-from-the-system-on-which-it-was-built

I am not expert on golang, no sure how your guys to cope with this? Any reason use a compile time base path? 

Here is how your code get data basePath:
	_, b, _, _ = runtime.Caller(0)
	basePath   = filepath.Dir(b)

One more question,  is this project still alive? I don't see any activities after initial commit.  Thank you.

**Comment by lryong** [comment]
Hi @GeniusWiki . `email-verifier` have dependency files but they are not mentioned in the README, we will update this later. 

We didn't notice this problem with cross-platform compilation when we were testing, and we also reproduced the problem you mentioned in our local environment, which we will try to fix recently. 

Finally, our project will always be maintained, we welcome any PR!

**Comment by GeniusWiki** [comment]
I don't have too much experience in Golang so no PR.  But I temporarily make that basePath = "." and put the data folder under same folder with compiled execution binary.  It is working for me, but I doubt it is not an ideal solution in Golang.

**Comment by lryong** [comment]
OK, I'll try to resolve this issue in a better way~

**Comment by lryong** [comment]
Hi, @GeniusWiki 
The latest version of `email-verifer` has fixed this issue

**Comment by GeniusWiki** [comment]
Tested and fixed.  Thank you for the quick turnaround.
