### ISSUE TITLE
Releasing the next version (1.3.3?)

### ISSUE THREAD

**Issue by lguminski** [AfterShip/email-verifier#80]
I can see that the last release is quite old, and given that recently there were a few changes (e.g. #75) it would be convenient to have a new version.

**Comment by lryong** [comment]
@lguminski Sorry for releasing v1.3.3 only now, we had new features merged together in the recent week and delayed to release the new version now. 
Generally if features are merged into the master branch, you can specify the commit record during installation if you want to use the new features first, see this: [How to point Go module dependency in go.mod to a latest commit in a repo?](https://stackoverflow.com/questions/53682247/how-to-point-go-module-dependency-in-go-mod-to-a-latest-commit-in-a-repo)

**Comment by lguminski** [comment]
@lryong I did that, but it's more convenient to have an official release. Thank you!
