### ISSUE TITLE
Initiate disposable domain list from the update URL

### ISSUE THREAD

**Issue by kriptor** [AfterShip/email-verifier#84]
Hi,

it would be really nice if you could make `updateDisposableDomains` optionally triggered when `EnableAutoUpdateDisposable` is called. This way one could initialize the map immediately instead of waiting for 24h. I know there is `AddDisposableDomains` and one could fetch from the same source and push it in... but due to [this](https://github.com/AfterShip/email-verifier/blob/aaa80fcae069dd6b92d7ec218de0d72eb3458448/handler.go#L64) it's then permanent which some may not want.

Cheers!

**Comment by lryong** [comment]
Hi @kriptor ,   the [lates version](https://github.com/AfterShip/email-verifier/releases/tag/v1.3.3) of email-verifier has supported updating disposable domains immediately once `EnableAutoUpdateDisposable()`, I think it will meet your needs, Hope you enjoy it!
