### ISSUE TITLE
Undefined variables and functions in verifier.go

### ISSUE THREAD

**Issue by Matrox100** [AfterShip/email-verifier#86]
Hello,

I'm having trouble building the email verifier program from the AfterShip repository. When I run the "go build" command in the terminal, I get the following error:

command-line-arguments
./verifier.go:15:24: undefined: schedule
./verifier.go:24:15: undefined: Syntax
./verifier.go:25:16: undefined: SMTP
./verifier.go:26:16: undefined: Gravatar
./verifier.go:39:17: undefined: disposableDomains
./verifier.go:40:3: undefined: disposableSyncDomains
./verifier.go:47:25: undefined: defaultFromEmail
./verifier.go:48:25: undefined: defaultHelloName
./verifier.go:58:14: undefined: reachableUnknown
./verifier.go:203:42: undefined: SMTP
./verifier.go:58:14: too many errors

It seems that the variables and functions used in the verifier.go file are undefined. I have tried running the "go get" command to download the necessary packages, but I still get the same error.

Could you please help me with this issue? I would greatly appreciate any assistance you can provide.

Thank you!

**Comment by lryong** [comment]
Can you provide your  detailed build command? for email-verifier is just a dependency library,  your have to build a `main.go `file and import this lib to use it's features

**Comment by Matrox100** [comment]
Hi,
Thank you for your feedback

I ran the following commands:
/opt/email-verifier/cmd/apiserver
go build -o emailverifier main.go
./emailverifier
But I can't reach the API

What am I doing wrong?
Thank you
